#!/usr/bin/env ruby
require 'erb'

def root_path
  File.expand_path( File.dirname( __FILE__ ))
end

def link( source, destination )
  `ln -nfs #{destination} #{source}`
end

def link_dotfile( source, destination )
  link source, "~/.dotfiles/#{destination}"
end

def generate( template_filename, evaluated_filename )
  #require 'pry'; binding.pry
  File.open "#{root_path}/#{evaluated_filename}", 'w' do |f|
    f.write ERB.new( File.read( "#{root_path}/#{template_filename}" )).result
  end
end

link_dotfile '~/.ansible.cfg', 'ansible.cfg'
link_dotfile '~/bin',          'bin'         
link_dotfile '~/.gemdandyrc',  'gemdandyrc'         
link_dotfile '~/.irbrc',       'irbrc'       
link_dotfile '~/.pryrc',       'pryrc'      
link_dotfile '~/.railsrc',     'railsrc'      
link_dotfile '~/.rvmrc',       'rvmrc'      
link_dotfile '~/.ssh/config',  'ssh/config'      
link_dotfile '~/.tmux.conf',   'tmux.conf'      
link_dotfile '~/.vimrc',       'vimrc'      
link_dotfile '~/.vimrc.d',     'vimrc.d'      
link_dotfile '~/.vim/colors',  'vim-themes'      
link_dotfile '~/.vim/snippets','snippets'      
link_dotfile '~/.zshrc',       'zshrc-osx'      

link '~/development', '/Volumes/Data/development'

generate     'gemrc.erb', 'gemrc-generated'
link_dotfile '~/.gemrc',  'gemrc-generated'         

generate     'gitconfig.erb', 'gitconfig-generated'
link_dotfile '~/.gitconfig',  'gitconfig-generated'         
