#!/usr/bin/env bash

BLACK=30
RED=31
GREEN=32
YELLOW=33
BLUE=34
MAGENTA=35
CYAN=36
LIGHT_GREY=37
DARK_GREY=90
LIGHT_RED=91
LIGHT_GREEN=92
LIGHT_YELLOW=93
LIGHT_BLUE=94
LIGHT_MAGENTA=95
LIGHT_CYAN=96

# Ask for the administrator password upfront
sudo -v

if ! command -v brew > /dev/null; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  brew update
fi

say() {
  if [ ! -z $2 ]; then
    COLOR=$2
  else
    COLOR=0
  fi

  echo -e "\033["$COLOR"m$1\033[0m"
}

say_dim() {
  echo -e "\033[2m$1\033[0m"
}

announce() {
  if [ ! -z $2 ]; then
    COLOR=$2
  else
    COLOR=0
  fi

  echo -en "\033["$COLOR"m$1 ...\033[0m"
}

perform() {
  command=$1
  output=`$command 2>&1`
  result=$?
  if [[ $result -eq 0 ]]; then
    echo -e "\033[32mOK\033[0m"
  else
    echo -e "\033[31mERROR\033[0m"
    echo -e "$output" >&2
    exit $result
  fi
}

brew_expand_alias() {
  brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

install_brew() {
  if brew_is_installed "$1"; then
    say "$1 brew already installed"
  else
    announce "Installing brew $1"
    perform "brew install $1"
  fi
}

install_cask() {
  if cask_is_installed "$1"; then
    say "$1 cask already installed"
  else
    announce "Installing cask $1" $CYAN
    perform "brew cask install $1"
  fi
}

brew_is_installed() {
  local name="$(brew_expand_alias "$1")"

  brew list -1 | grep -Fqx "$name"
}

cask_is_installed() {
  brew cask list -1 | grep -Fqx "$1"
}

brew_is_upgradable() {
  local name="$(brew_expand_alias "$1")"

  brew outdated --quiet "$name" >/dev/null
  [[ $? -ne 0 ]]
}

DATA_VOLUME=/Volumes/Data
ln -nfs $DATA_VOLUME/.api-tokens.yml .api-tokens.yml
ln -nfs $DATA_VOLUME/.digital-ocean .digital-ocean
ln -nfs $DATA_VOLUME/.do-not-delete-gvtus .do-not-delete-gvtus
ln -nfs $DATA_VOLUME/.do-not-delete-gvtus-2 .do-not-delete-gvtus-2
ln -nfs $DATA_VOLUME/.ey-cloud.yml .ey-cloud.yml
ln -nfs $DATA_VOLUME/.eyrc .eyrc
ln -nfs $DATA_VOLUME/.guardrc .guardrc
ln -nfs $DATA_VOLUME/.guard_history .guard_history
ln -nfs $DATA_VOLUME/.irb-history .irb-history
ln -nfs $DATA_VOLUME/.pry_history .pry_history
ln -nfs $DATA_VOLUME/.s3-credentials.yml .s3-credentials.yml
ln -nfs $DATA_VOLUME/.s3cfg .s3cfg
ln -nfs $DATA_VOLUME/.zsh_history .zsh_history

install_brew 'ctags'
install_brew 'dnsmasq'
install_brew 'git'
install_brew 'git-crypt'
install_brew 'tmux'
install_brew 'vim'
install_brew 'wget'

install_brew 'caskroom/cask/brew-cask'

install_cask 'adium'
install_cask 'alfred'
install_cask 'dropbox'
install_cask 'evernote'
install_cask 'forklift'
install_cask 'google-chrome'
install_cask 'iterm2'
install_cask 'kaleidoscope'
install_cask 'navicat-premium'
install_cask 'onepassword'
install_cask 'parallels-desktop'
install_cask 'sublime-text'
install_cask 'tower'
install_cask 'tunnelblick'
install_cask 'tower'
install_cask 'textexpander'
install_cask 'vmware-fusion'

ZSH_DIRECTORY=~/.oh-my-zsh
if [ ! -d "$ZSH_DIRECTORY" ]; then
  git clone git@github.com:midas/oh-my-zsh.git $ZSH_DIRECTORY
  cd $ZSH_DIRECTORY
  git checkout jason
else
  say "oh-my-zsh already installed"
fi

if [[ "$SHELL" != */zsh ]]; then
  say "Changing shell to zsh"
  chsh -s $(which zsh)
fi

DOTFILES_DIRECTORY=~/.dotfiles
if [ ! -d "$DOTFILES_DIRECTORY" ]; then
  git clone git@github.com:midas/dotfiles.git $DOTFILES_DIRECTORY
  $DOTFILES_DIRECTORY/bootstrap
else
  say "dotfiles already installed"
fi

NEOBUNDLE_DIRECTORY=~/.vim/bundle/neobundle.vim
if [ ! -d "$NEOBUNDLE_DIRECTORY" ]; then
  mkdir -p ~/.vim/bundle
  git clone https://github.com/Shougo/neobundle.vim $NEOBUNDLE_DIRECTORY
else
  say "Neobundle already installed"
fi

# Install RVM
rvm --version > /dev/null
if [ $? != 0 ]; then
  install_brew 'gpg2'
  gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
  \curl -sSL https://get.rvm.io | bash -s stable
else
  say "RVM already installed"
fi

say "Configuring Bundler for faster, parallel gem installation ..."
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

if [ ! -f ~/Library/Fonts/Monaco+for+Powerline.otf ]; then
  open $DOTFILES_DIRECTORY/powerline-fonts/Monaco+for+Powerline.otf
else
  say "Monaco+for+Powerline.otf already installed"
fi

USR_LOCAL_ETC_DIR=/usr/local/etc
DOTFILES_USR_LOCAL_ETC_DIR=$DOTFILES_DIRECTORY/usr/local/etc
cd $USR_LOCAL_ETC_DIR
ln -nfs $DOTFILES_USR_LOCAL_ETC_DIR/dnsmasq.conf dnsmasq.conf
ln -nfs $DOTFILES_USR_LOCAL_ETC_DIR/dnsmasq-resolv.conf dnsmasq-resolv.conf
cd ~

# Set sidebar icon size to medium
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Remove duplicates in the “Open With” menu (also see `lscleanup` alias)
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# Disable Resume system-wide
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 0

###############################################################################
# Screen                                                                      #
###############################################################################

# Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Desktop"

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

###############################################################################
# Finder                                                                      #
###############################################################################

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfDe"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"

# Finder: show hidden files by default
#defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Show the ~/Library folder
chflags nohidden ~/Library

###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################

# Set the icon size of Dock items to 36 pixels
defaults write com.apple.dock tilesize -int 36
defaults write com.apple.dock orientation -string "left"

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

# Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0
# Remove the animation when hiding/showing the Dock
#defaults write com.apple.dock autohide-time-modifier -float 0

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# Top left screen corner → Mission Control
defaults write com.apple.dock wvous-tl-corner -int 0
defaults write com.apple.dock wvous-tl-modifier -int 0
# Top right screen corner → Desktop
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0
# Bottom left screen corner → Start screen saver
defaults write com.apple.dock wvous-bl-corner -int 5
defaults write com.apple.dock wvous-bl-modifier -int 0

###############################################################################
# Time Machine                                                                #
###############################################################################

# Prevent Time Machine from prompting to use new hard drives as backup volume
#defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable local Time Machine backups
hash tmutil &> /dev/null && sudo tmutil disablelocal

###############################################################################
# Google Chrome & Google Chrome Canary                                        #
###############################################################################

# Disable the all too sensitive backswipe
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false

# Use the system-native print preview dialog
defaults write com.google.Chrome DisablePrintPreview -bool true
defaults write com.google.Chrome.canary DisablePrintPreview -bool true

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
	"Dock" "Finder" "Mail" "Messages" "SizeUp" "SystemUIServer" \
	"Transmission" "Twitter" "iCal"; do
	killall "${app}" > /dev/null 2>&1
done
echo "Done. Note that some of these changes require a logout/restart to take effect."
